# Development environment override
services:
  proxy:
    volumes:
      - ./docker/certs:/etc/nginx/certs

  varnish:
    build:
      context: ./docker/varnish

  php:
    build:
      context: ./api
      target: php_dev
    volumes:
      - ./api:/app
      - /app/var
      - ./api/php-fpm/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      APP_SECRET: ${XDEBUG_MODE:-!ChangeMe!}
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  pwa:
    build:
      context: ./pwa
      target: dev
    volumes:
      - ./pwa:/srv/app
    environment:
      API_PLATFORM_CREATE_CLIENT_ENTRYPOINT: ${API_SERVER_NAME-api.localhost}
      API_PLATFORM_CREATE_CLIENT_OUTPUT: .
      # On Linux, you may want to comment the following line for improved performance
      WATCHPACK_POLLING: "true"

###> doctrine/doctrine-bundle ###
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

