# Production environment override
services:
  php:
    build:
      context: ./api
      target: php_prod
    environment:
      APP_SECRET: ${APP_SECRET}

  pwa:
    build:
      context: ./pwa
      target: prod

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
